version: "3.7"

services:
  db:
    image: postgres:11
    env_file: 
      - ./envs/db.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend
    tty: true 

  