version: "3.7"

services:
  db:
    image: postgres:11
    env_file: 
      - ./envs/db.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "4000:4000"
    env_file:
      - ./envs/db.env
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_POLLINTERVAL=3000
      - NODE_ENV=development
    volumes: 
      - "./backend/src:/usr/backend/src"
    
